services:
  sim:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros_jazzy:vnc
    container_name: ros_gui
    tty: true
    stdin_open: true
    environment:
      - VNC_GEOMETRY=1600x900
      - PATH=/dev-scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
      - "127.0.0.1:5901:5901"
      - "127.0.0.1:6080:6080"
    volumes:
      # my ROS workspace (edit locally, build inside)
      - ../ros2_ws:/ws
      # your local scripts into PATH inside container
      - ./dev-scripts:/dev-scripts:ro